version: '2'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - mynetwork
  DevOps_Project:
    #container_name: my-spring-app
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - "8082:8082"
    volumes:
      - .m2:/root/.m2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/devopsdb?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - spring.jpa.show-sql=true
      - spring.jpa.hibernate.ddl-auto=update
    stdin_open: true
    tty: true
    networks:
      - mynetwork
volumes:
  db:
networks:
  mynetwork:
