version: '2'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=devopsdb
      - MYSQL_ROOT_PASSWORD=root
  app:
    container_name: spring
    image: spring-boot
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - "8082:8082"
    volumes:
      - .m2:/root/.m2
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/devopsdb?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"}'
    stdin_open: true
    tty: true
volumes:
  db:

