version: '3.8'
services:
  mysqlDev-container:
    container_name: mysqlDev-container
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - sqldata:/var/lib/mysql

  devops_project:
    container_name: devops_project
    image: wassimdhaouadi/devops_project 
    restart: on-failure
    depends_on:
      - mysqlDev-container
    command: ["./wait-for-it.sh", "mysqlDev-container:3306", "java", "-jar", "/devops_project.jar"]
    ports:
      - "8765:8765"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  sqldata:

networks:
  my-network:  
    external: true