version: '2'
services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - sqldata:/var/lib/mysql
  devops-project:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    image: spring-boot
    ports:
      - "8082:8083"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  sqldata:
