version: '3.8'
services:
  devops_project:
    container_name: devops_project
    image: wassimdhaouadi/devops_project
    restart: on-failure
    depends_on:
      - mysqldb
    ports:
      - "8765:8765"
    volumes:
      - .m2:/root/.m2
    build: .
  mysqldb:
    container_name: mysqldb
    image: "mysql:5.7"
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "devopsapp"
    ports:
      - "3307:3306"  
    