version: '2'
services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
  devops-project:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - "8082:8082"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db:
